; IRIS Complete LLVM IR — phase 49
; Struct/array types lowered, typed calls, alloca for fixed arrays.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-gnu"

@.str.0 = private unnamed_addr constant [8 x i8] c"Hello, \00", align 1
@.str.1 = private unnamed_addr constant [2 x i8] c"!\00", align 1
@.str.2 = private unnamed_addr constant [6 x i8] c"World\00", align 1
@.str.3 = private unnamed_addr constant [5 x i8] c"IRIS\00", align 1
@.str.4 = private unnamed_addr constant [9 x i8] c"Compiler\00", align 1

declare void @iris_print(ptr)
declare void @iris_print_i64(i64)
declare void @iris_print_i32(i32)
declare void @iris_print_f64(double)
declare void @iris_print_f32(float)
declare void @iris_print_bool(i1)
declare void @iris_print_str(ptr)
declare void @iris_panic(ptr)
declare ptr @iris_read_line()
declare i64 @iris_read_i64()
declare double @iris_read_f64()
declare i64 @iris_str_len(ptr)
declare ptr @iris_str_concat(ptr, ptr)
declare i1 @iris_str_eq(ptr, ptr)
declare i1 @iris_str_contains(ptr, ptr)
declare i1 @iris_str_starts_with(ptr, ptr)
declare i1 @iris_str_ends_with(ptr, ptr)
declare ptr @iris_str_to_upper(ptr)
declare ptr @iris_str_to_lower(ptr)
declare ptr @iris_str_trim(ptr)
declare ptr @iris_str_repeat(ptr, i64)
declare ptr @iris_value_to_str(ptr)
declare ptr @iris_parse_i64(ptr)
declare ptr @iris_parse_f64(ptr)
declare i64 @iris_str_index(ptr, i64)
declare ptr @iris_str_slice(ptr, i64, i64)
declare ptr @iris_str_find(ptr, ptr)
declare ptr @iris_str_replace(ptr, ptr, ptr)
declare ptr @iris_const_str()
declare ptr @iris_make_some(ptr)
declare ptr @iris_make_none()
declare i1 @iris_is_some(ptr)
declare ptr @iris_option_unwrap(ptr)
declare ptr @iris_make_ok(ptr)
declare ptr @iris_make_err(ptr)
declare i1 @iris_is_ok(ptr)
declare ptr @iris_result_unwrap(ptr)
declare ptr @iris_result_unwrap_err(ptr)
declare ptr @iris_list_new()
declare void @iris_list_push(ptr, ptr)
declare i64 @iris_list_len(ptr)
declare ptr @iris_list_get(ptr, i64)
declare void @iris_list_set(ptr, i64, ptr)
declare ptr @iris_list_pop(ptr)
declare ptr @iris_map_new()
declare void @iris_map_set(ptr, ptr, ptr)
declare ptr @iris_map_get(ptr, ptr)
declare i1 @iris_map_contains(ptr, ptr)
declare void @iris_map_remove(ptr, ptr)
declare i64 @iris_map_len(ptr)
declare i1 @iris_list_contains(ptr, ptr)
declare void @iris_list_sort(ptr)
declare ptr @iris_map_keys(ptr)
declare ptr @iris_map_values(ptr)
declare ptr @iris_list_concat(ptr, ptr)
declare ptr @iris_list_slice(ptr, i64, i64)
declare ptr @iris_file_read_all(ptr)
declare ptr @iris_file_write_all(ptr, ptr)
declare i1 @iris_file_exists(ptr)
declare ptr @iris_file_lines(ptr)
declare i64 @iris_db_open(ptr)
declare i64 @iris_db_exec(i64, ptr)
declare ptr @iris_db_query(i64, ptr)
declare i64 @iris_db_close(i64)
declare void @exit(i32)
declare ptr @malloc(i64)
declare void @free(ptr)
declare void @iris_set_argv(i32, ptr)
declare ptr @iris_process_args()
declare ptr @iris_env_var(ptr)
declare ptr @iris_alloc_array()
declare ptr @iris_array_load(ptr, i64)
declare void @iris_array_store(ptr, i64, ptr)
declare ptr @iris_tensor_op()
declare ptr @iris_tensor_load(ptr, ...)
declare void @iris_tensor_store(ptr, ...)
declare ptr @iris_tensor_matmul(ptr, ptr)
declare ptr @iris_tensor_add(ptr, ptr)
declare ptr @iris_tensor_sub(ptr, ptr)
declare ptr @iris_tensor_mul(ptr, ptr)
declare ptr @iris_tensor_div(ptr, ptr)
declare ptr @iris_tensor_neg(ptr)
declare ptr @iris_tensor_relu(ptr)
declare ptr @iris_tensor_sigmoid(ptr)
declare ptr @iris_tensor_tanh_act(ptr)
declare ptr @iris_tensor_exp(ptr)
declare ptr @iris_tensor_log(ptr)
declare ptr @iris_tensor_sqrt(ptr)
declare ptr @iris_tensor_abs(ptr)
declare ptr @iris_tensor_reshape(ptr, i32, ptr)
declare ptr @iris_tensor_transpose(ptr, i32, ptr)
declare ptr @iris_tensor_reduce_sum(ptr, i32, i32)
declare ptr @iris_tensor_reduce_max(ptr, i32, i32)
declare ptr @iris_tensor_reduce_mean(ptr, i32, i32)
declare void @iris_retain(ptr)
declare void @iris_release(ptr)
declare void @iris_retain_kind(ptr, i32)
declare void @iris_release_kind(ptr, i32)
declare ptr @iris_chan_new()
declare void @iris_chan_send(ptr, ptr)
declare ptr @iris_chan_recv(ptr)
declare void @iris_spawn_fn(ptr, ptr)
declare void @iris_par_for(ptr, i64, i64)
declare void @iris_barrier()
declare ptr @iris_make_struct(i32, ...)
declare ptr @iris_get_field(ptr, i32)
declare ptr @iris_make_tuple(i32, ...)
declare ptr @iris_get_element(ptr, i32)
declare ptr @iris_make_closure(ptr, i32, ...)
declare ptr @iris_call_closure(ptr, ...)
declare void @iris_call_closure_void(ptr, ...)
declare ptr @iris_closure_fn(ptr)
declare ptr @iris_closure_get_capture(ptr, i32)
declare ptr @iris_atomic_new(ptr)
declare ptr @iris_atomic_load(ptr)
declare void @iris_atomic_store(ptr, ptr)
declare ptr @iris_atomic_add(ptr, ptr)
declare ptr @iris_mutex_new()
declare ptr @iris_mutex_lock(ptr)
declare void @iris_mutex_unlock(ptr)
declare ptr @iris_make_grad(double, double)
declare double @iris_grad_value(ptr)
declare double @iris_grad_tangent(ptr)
declare ptr @iris_tape_record(double, ptr, i64, ptr, ptr)
declare void @iris_backward(ptr)
declare double @iris_tape_grad(ptr)
declare ptr @iris_sparsify(ptr)
declare ptr @iris_densify(ptr)
declare ptr @iris_box_i64(i64)
declare ptr @iris_box_i32(i32)
declare ptr @iris_box_f64(double)
declare ptr @iris_box_f32(float)
declare ptr @iris_box_bool(i1)
declare ptr @iris_box_str(ptr)
declare ptr @iris_box_list(ptr)
declare ptr @iris_box_map(ptr)
declare ptr @iris_box_option(ptr)
declare ptr @iris_box_result(ptr)
declare ptr @iris_box_chan(ptr)
declare ptr @iris_box_atomic(ptr)
declare ptr @iris_box_mutex(ptr)
declare ptr @iris_box_grad(ptr)
declare ptr @iris_box_sparse(ptr)
declare i64 @iris_unbox_i64(ptr)
declare double @iris_unbox_f64(ptr)
declare i32 @iris_unbox_bool(ptr)
declare ptr @iris_unbox_str(ptr)
declare ptr @iris_unbox_list(ptr)
declare ptr @iris_unbox_map(ptr)
declare ptr @iris_unbox_option(ptr)
declare ptr @iris_unbox_result(ptr)
declare ptr @iris_unbox_chan(ptr)
declare ptr @iris_unbox_atomic(ptr)
declare ptr @iris_unbox_mutex(ptr)
declare ptr @iris_unbox_grad(ptr)
declare ptr @iris_unbox_sparse(ptr)
declare ptr @iris_i64_to_str(i64)
declare ptr @iris_i32_to_str(i32)
declare ptr @iris_f64_to_str(double)
declare ptr @iris_f32_to_str(float)
declare ptr @iris_bool_to_str(i1)
declare ptr @iris_str_to_str(ptr)
declare i64 @iris_pow_i64(i64, i64)
declare i64 @iris_min_i64(i64, i64)
declare i64 @iris_max_i64(i64, i64)
declare i64 @iris_abs_i64(i64)
declare double @iris_sign_f64(double)
declare double @tan(double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.fabs.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.round.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.exp.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.log2.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)
declare ptr @iris_str_split(ptr, ptr)
declare ptr @iris_str_join(ptr, ptr)
declare i64 @iris_now_ms()
declare void @iris_sleep_ms(i64)
declare i64 @iris_tcp_connect(ptr, i64)
declare i64 @iris_tcp_listen(i64)
declare i64 @iris_tcp_accept(i64)
declare ptr @iris_tcp_read(i64)
declare void @iris_tcp_write(i64, ptr)
declare void @iris_tcp_close(i64)
declare i64 @iris_udp_open(i64)
declare void @iris_udp_send(i64, ptr, i64)
declare ptr @iris_udp_recv(i64)
declare void @iris_udp_close(i64)
declare ptr @iris_http_get(ptr)
declare ptr @iris_http_post(ptr, ptr, ptr)
declare ptr @iris_http_post_json(ptr, ptr)
declare ptr @iris_http_request(ptr, ptr, ptr, ptr)
declare ptr @iris_json_parse(ptr)
declare ptr @iris_json_stringify(ptr)
declare ptr @iris_set_new()
declare ptr @iris_set_add(ptr, ptr)
declare i1 @iris_set_contains(ptr, ptr)
declare ptr @iris_set_remove(ptr, ptr)
declare i64 @iris_set_len(ptr)
declare ptr @iris_set_to_list(ptr)
declare i1 @iris_regex_match(ptr, ptr)
declare ptr @iris_regex_find_all(ptr, ptr)
declare ptr @iris_regex_replace(ptr, ptr, ptr)
declare ptr @iris_datetime_now()
declare double @iris_datetime_timestamp()
declare ptr @iris_datetime_format(ptr)
declare ptr @iris_cwd()
declare ptr @iris_listdir(ptr)
declare ptr @iris_path_join(ptr, ptr)
declare i1 @iris_path_exists(ptr)
declare i1 @iris_mkdir(ptr)
declare i1 @iris_remove_file(ptr)
declare ptr @iris_type_of(ptr)
declare double @iris_random()
declare i64 @iris_random_range(i64, i64)
declare i64 @iris_hash(ptr)
declare ptr @iris_base64_encode(ptr)
declare ptr @iris_base64_decode(ptr)
declare ptr @iris_char_at(ptr, i64)
declare ptr @iris_str_reverse(ptr)
declare ptr @iris_str_pad_left(ptr, i64, ptr)
declare ptr @iris_str_pad_right(ptr, i64, ptr)
declare ptr @iris_str_chars(ptr)
declare ptr @iris_str_bytes(ptr)
declare i64 @iris_str_count(ptr, ptr)
declare double @iris_math_pi()
declare double @iris_math_e()
declare double @iris_math_inf()
declare i1 @iris_is_nan(double)
declare i1 @iris_is_inf(double)
declare ptr @iris_env_get(ptr)
declare void @iris_env_set(ptr, ptr)
declare void @iris_exit_code(i64)
declare ptr @iris_exec_cmd(ptr)
declare i64 @iris_pid()
declare ptr @iris_uuid()
declare ptr @iris_sha256(ptr)
declare ptr @iris_hex_encode(ptr)
declare ptr @iris_hex_decode(ptr)
declare ptr @iris_deque_new()
declare void @iris_deque_push_front(ptr, ptr)
declare void @iris_deque_push_back(ptr, ptr)
declare ptr @iris_deque_pop_front(ptr)
declare ptr @iris_deque_pop_back(ptr)
declare i64 @iris_deque_len(ptr)
declare ptr @iris_ffi_open(ptr)
declare i64 @iris_ffi_call(ptr, ptr)
declare i1 @iris_ffi_close(ptr)
declare i64 @iris_ffi_call_i64(ptr, ptr, ptr, i32)
declare double @iris_ffi_call_f64(ptr, ptr, ptr, i32)
declare ptr @iris_ffi_call_str(ptr, ptr, ptr, i32)
declare void @iris_ffi_call_void(ptr, ptr, ptr, i32)
declare ptr @iris_python_eval(ptr)
declare i64 @iris_python_exec(ptr)
declare ptr @iris_python_call(ptr, ptr, ptr)
declare ptr @iris_python_version()
declare ptr @iris_rust_lib_open(ptr)
declare i64 @iris_rust_call_i64(ptr, ptr, ptr, i32)
declare double @iris_rust_call_f64(ptr, ptr, ptr, i32)
declare void @iris_rust_call_void(ptr, ptr, ptr, i32)
declare double @iris_list_sum(ptr)
declare i64 @iris_list_min(ptr)
declare i64 @iris_list_max(ptr)
declare i64 @iris_list_index_of(ptr, i64)
declare i64 @iris_list_count(ptr, i64)
declare ptr @iris_list_reverse(ptr)
declare ptr @iris_list_take(ptr, i64)
declare ptr @iris_list_drop(ptr, i64)
declare ptr @iris_deque_front(ptr)
declare ptr @iris_deque_back(ptr)
declare ptr @iris_chan_try_recv(ptr)
declare i64 @iris_chan_len(ptr)
declare i64 @iris_select(ptr, ...)
declare i1 @iris_timeout(i64)
declare i64 @iris_ffi_call_args(ptr, ptr, ptr, i32)
declare i64 @iris_thread_count()
declare i64 @iris_read_key()
declare ptr @iris_read_password(ptr)
declare void @iris_term_clear()
declare void @iris_term_cursor(i64, i64)
declare void @iris_term_show_cursor(i32)
declare void @iris_term_set_color(i64, i64)
declare void @iris_term_reset()
declare i64 @iris_term_rows()
declare i64 @iris_term_cols()

define ptr @greet(ptr %name) nounwind willreturn {
entry0:
  %v1 = getelementptr inbounds [8 x i8], ptr @.str.0, i32 0, i32 0
  %v2 = call ptr @iris_str_to_str(ptr %name)
  %v3 = getelementptr inbounds [2 x i8], ptr @.str.1, i32 0, i32 0
  %v4 = call ptr @iris_str_concat(ptr %v2, ptr %v3)
  %v5 = call ptr @iris_str_concat(ptr %v1, ptr %v4)
  ret ptr %v5
}

define i64 @main() {
entry0:
  %v0 = getelementptr inbounds [6 x i8], ptr @.str.2, i32 0, i32 0
  %v10 = getelementptr inbounds [8 x i8], ptr @.str.0, i32 0, i32 0
  %v11 = call ptr @iris_str_to_str(ptr %v0)
  %v12 = getelementptr inbounds [2 x i8], ptr @.str.1, i32 0, i32 0
  %v13 = call ptr @iris_str_concat(ptr %v11, ptr %v12)
  %v14 = call ptr @iris_str_concat(ptr %v10, ptr %v13)
  call void @iris_print_str(ptr %v14)
  %v3 = getelementptr inbounds [5 x i8], ptr @.str.3, i32 0, i32 0
  %v15 = getelementptr inbounds [8 x i8], ptr @.str.0, i32 0, i32 0
  %v16 = call ptr @iris_str_to_str(ptr %v3)
  %v17 = getelementptr inbounds [2 x i8], ptr @.str.1, i32 0, i32 0
  %v18 = call ptr @iris_str_concat(ptr %v16, ptr %v17)
  %v19 = call ptr @iris_str_concat(ptr %v15, ptr %v18)
  call void @iris_print_str(ptr %v19)
  %v6 = getelementptr inbounds [9 x i8], ptr @.str.4, i32 0, i32 0
  %v20 = getelementptr inbounds [8 x i8], ptr @.str.0, i32 0, i32 0
  %v21 = call ptr @iris_str_to_str(ptr %v6)
  %v22 = getelementptr inbounds [2 x i8], ptr @.str.1, i32 0, i32 0
  %v23 = call ptr @iris_str_concat(ptr %v21, ptr %v22)
  %v24 = call ptr @iris_str_concat(ptr %v20, ptr %v23)
  call void @iris_print_str(ptr %v24)
  ret i64 0
}

